using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Utils
{
    public class PersistentObjectInitializer : MonoBehaviour
    {
        /* 
         * this script is currently not in use. This is needed when we want to return to the Start screen when quitting.
         * Now, we just quit the application.
         * TODO: let this work (atm some singletons are auto-generated by Unity, which gives two instances and messes 
         *       up the references to the instance.
         */

        [SerializeField] private GameObject[] _persistentObjects = null;

        private void Awake()
        {
            foreach (GameObject persistentObject in _persistentObjects)
            {
                GameObject instance = Instantiate(persistentObject);
                DontDestroyOnLoad(instance);
            }
            Destroy(gameObject);
        }
    }
}